name: OctoPrint Proxy (NOT WORKING)
version: 1.0.3
slug: octoprint_proxy
description: Access OctoPrint from within Home Assistant
url: https://github.com/MaxWinterstein/homeassistant-addons/
image: ghcr.io/maxwinterstein/homeassistant-addon-octoprint-proxy-{arch}
ingress: true
ingress_port: 8055
ingress_entry: login
panel_title: OctoPrint
panel_icon: mdi:printer-3d-nozzle
arch:
  - armv7
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
ports:
  8055/tcp: 8055
