name: OctoPrint Proxy
version: 1.0.1
slug: octoprint_proxy
description: Access OctoPrint from within Home Assistant
url: https://github.com/MaxWinterstein/homeassistant-addons/
ingress: true
ingress_port: 80
panel_title: OctoPrint
panel_icon: mdi:printer-3d-nozzle
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: application
boot: auto
init: false
options:
  octoprint_host: octopi
  octoprint_port: '443'
  ssl:
    enabled: true
    verify: false
schema:
  octoprint_host: str
  octoprint_port: port
  ssl:
    enabled: bool
    verify: bool
hassio_api: false
