# AUTO BUILDS #
# From https://github.com/Poeschl/Hassio-Addons
# name: slug/filename ; could be slug/config.* for all files
adsb-multi-portal-feeder: adsb-multi-portal-feeder/config.* # Image : yes
angryipscanner: angryipscanner/config.* # Image : yes
toogoodtogo-ha-mqtt-bridge: toogoodtogo-ha-mqtt-bridge/config.*
