#!/usr/bin/env bashio

bashio::log.info "Exporting log level for nodejs: $(bashio::config log_level)"
export NODE_CONSOLE_LOG_LEVEL=`bashio::config log_level`

bashio::log.info "Symlinking data dir"
mkdir -p /share/eufy-ha-mqtt-bridge/data
rm -rf /app/data
ln -s /share/eufy-ha-mqtt-bridge/data /app # symlink data mount from share 

bashio::log.info "Generating config.yml from options.json"
echo '# Generated by homeassistant, do not edit!' > /app/data/config.yml
echo '# Edit configuration only at the Add-on configuration tab!' >> /app/data/config.yml
json2yml /data/options.json >> /app/data/config.yml

bashio::log.info "Image build with version $(cat /version)"

bashio::log.info "starting original stuff..."
npm run start