version: 0.1.0
slug: angryipscanner
name: Angry IP Scanner
description: Fast and friendly network scanner
url: https://github.com/MaxWinterstein/homeassistant-addons/
arch:
  - amd64
  - armhf
  - aarch64
ingress: true
ingress_entry: novnc/vnc_lite.html?scale=yes
init: false
host_network: true
panel_icon: mdi:ip
ports:
  5900/tcp: null
ports_description:
  5900/tcp: Angry IP Scanner via VNC (Not required for Ingress. Not secure!)
map:
  - share:rw
