name: eufy_manually_build_image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Image Tag"
        required: true

jobs:
  eufy-ha-mqtt-bridge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --aarch64 \
            --target eufy-ha-mqtt-bridge \
            --docker-hub maxwinterstein
